---
title: Natural Language Processing for Fuzzy String Matching with Python   
author: 
date: 2019-05-26
slug: 
categories: 
- languageprocessing
- python
- media
- fuzzy
- datascience
- AI
tags: 
- languageprocessing
- python
- media
- fuzzy
- datascience
- AI
isCJKLanguage: no 
---

## Natural Language Processing for Fuzzy String Matching with Python   
[ <a href="https://medium.com/@actsusanli/natural-language-processing-for-fuzzy-string-matching-with-python-6632b7824c49" target="_blank">read more</a> ] 
  In computer science, fuzzy string matching is the technique of finding strings that match a pattern… 5 min read 




## JIT fast! Supercharge tensor processing in Python with JIT compilation   
[ <a href="https://medium.com/@chrisvcsefalvay/jit-fast-supercharge-tensor-processing-in-python-with-jit-compilation-47598de6ee96" target="_blank">read more</a> ] 
  Numba can speed up tensor processing work in Python by an order of magnitude. Read on for one of the easiest… 11 min read 




## Machine Learning | Natural Language Preprocessing with Python   
[ <a href="https://medium.com/@mateusz.jurewicz/machine-learning-natural-language-preprocessing-with-python-5922d79d9ee2" target="_blank">read more</a> ] 
  5 Helpful Tips 9 min read 




## Simplifying Sentiment Analysis using VADER in Python (on Social Media Text)   
[ <a href="https://medium.com/@parulnith/simplifying-social-media-sentiment-analysis-using-vader-in-python-f9e6ec6fc52f" target="_blank">read more</a> ] 
  An easy to use Python library built especially for sentiment analysis of social media texts. 8 min read 




## 'Automated Analysis and the AI Race (Barbara Matthews)' 
 [ <a href="https://www.finextra.com/blogposting/17251/automated-analysis-and-the-ai-race?utm_medium=rssfinextra&utm_source=finextrablogs" target="_blank">read more</a> ]
This post is adapted from a March 2019 blog at www.bcmstrategy2.com.
Artificial Intelligence (AI).  Everyone either wants to use it or fret about robots running the world.  Whether its the fourth industrial revolution
 under discussion at the World Economic… [+9371 chars] 


