---
title: Why are developers still using Angular?   
author: 
date: 2019-05-27
slug: 
categories: 
- textsummarization
- approach
- react
- datascience
- AI
tags: 
- textsummarization
- approach
- react
- datascience
- AI
isCJKLanguage: no 
---

## Why are developers still using Angular?   
[ <a href="" target="_blank">read more</a> ] 
  especially when everyone seems to be wanting React 4 min read 




## Text Mining 101: A Stepwise Introduction to Topic Modeling using Latent…   
[ <a href="https://medium.com/@prateekjoshi565/text-mining-101-a-stepwise-introduction-to-topic-modeling-using-latent-semantic-analysis-using-add9c905efd9" target="_blank">read more</a> ] 
  Have you ever been inside a well-maintained library? I'm always incredibly impressed with the way the… 10 min read 




## Unsupervised Text Summarization using Sentence Embeddings   
[ <a href="https://medium.com/@kushalchauhan/unsupervised-text-summarization-using-sentence-embeddings-adb15ce83db1" target="_blank">read more</a> ] 
  I will describe the approach that I used to perform Text Summarization on a multi language dataset of… 13 min read 




## Sentiment analysis : Machine-Learning approach   
[ <a href="https://medium.com/@samuelpilcer/sentiment-analysis-machine-learning-approach-83e4ba38b57" target="_blank">read more</a> ] 
  Second blog post published on my Data Science project for Reputation.com 8 min read 




## 'Want to Know Your Wine Is Genuine? EY Has Built a Blockchain for That' 
 [ <a href="https://www.coindesk.com/want-to-know-your-wine-is-genuine-ey-has-built-a-blockchain-for-that" target="_blank">read more</a> ]
Big Four professional services firm EY has built a blockchain platform for a firm that will help consumers determine wines’ quality, provenance and authenticity.
The TATTOO Wine Platform has been developed for Blockchain Wine Pte. Ltd. using EYs OpsChain sol… [+1749 chars] 


