---
title: "Value-based drafting for Wide Receiver in Standard and PPR in the 2019 Fantasy…  " 
author: 
date: 2019-09-22
slug: 
categories: 
- wide
- key
- learning
- ai
- datascience
- AI
tags: 
- wide
- key
- learning
- ai
- datascience
- AI
isCJKLanguage: no 
---

## Value-based drafting for Wide Receiver in Standard and PPR in the 2019 Fantasy…   
[ <a href="https://medium.com/@chriseal/value-based-drafting-for-wide-receiver-in-standard-and-ppr-in-the-2019-fantasy-football-season-aea916090867" target="_blank">read more</a> ] 
  According to our machine learning models and the Fantasy Outliers team, these Wide Receivers could return… 5 min read 




## How does Ethereum work, anyway?   
[ <a href="" target="_blank">read more</a> ] 
  Introduction 33 min read 




## Helm 3: Fun With the New Beta   
[ <a href="https://medium.com/@chriscooney/helm-3-fun-with-the-new-beta-8f91c70891ff" target="_blank">read more</a> ] 
  Cleaner, simpler and more secure, with the previous functions you love 4 min read 




## Generative AI: A Key to Machine Intelligence?   
[ <a href="" target="_blank">read more</a> ] 
  We're living in the age of the next industrial revolution: the very first three had freed most of the humans… 12 min read 




## 'CipherTrace Scout App Takes Crypto Investigations Mobile' 
 [ <a href="https://www.coindesk.com/ciphertrace-scout-app-takes-crypto-investigations-mobile" target="_blank">read more</a> ]
Blockchain forensics firm CipherTrace has developed a mobile tool for flagging bitcoin and ethereum tokens with a criminal past.
Announced today, CipherTrace Scout grants street-level investigators more freedom to identify, track and document illicit crypto … [+3938 chars] 


