---
title: Natural Language Processing for Fuzzy String Matching with Python   
author: 
date: 2019-05-26
slug: 
categories: 
- languageprocessing
- python
- media
- fuzzy
- datascience
- AI
tags: 
- languageprocessing
- python
- media
- fuzzy
- datascience
- AI
isCJKLanguage: no 
---

## Natural Language Processing for Fuzzy String Matching with Python   
[ <a href="https://medium.com/@actsusanli/natural-language-processing-for-fuzzy-string-matching-with-python-6632b7824c49" target="_blank">read more</a> ] 
  In computer science, fuzzy string matching is the technique of finding strings that match a pattern… 5 min read 




## JIT fast! Supercharge tensor processing in Python with JIT compilation   
[ <a href="https://medium.com/@chrisvcsefalvay/jit-fast-supercharge-tensor-processing-in-python-with-jit-compilation-47598de6ee96" target="_blank">read more</a> ] 
  Numba can speed up tensor processing work in Python by an order of magnitude. Read on for one of the easiest… 11 min read 




## Machine Learning | Natural Language Preprocessing with Python   
[ <a href="https://medium.com/@mateusz.jurewicz/machine-learning-natural-language-preprocessing-with-python-5922d79d9ee2" target="_blank">read more</a> ] 
  5 Helpful Tips 9 min read 




## Simplifying Sentiment Analysis using VADER in Python (on Social Media Text)   
[ <a href="https://medium.com/@parulnith/simplifying-social-media-sentiment-analysis-using-vader-in-python-f9e6ec6fc52f" target="_blank">read more</a> ] 
  An easy to use Python library built especially for sentiment analysis of social media texts. 8 min read 




## 'The Implementation of Robotic Process Automation (RPA) in Companies can Help Reduce Offshore and Onshore Operations Cost by More Than 25% in Most of the Cases: IndustryARC' 
 [ <a href="https://www.prnewswire.com/news-releases/the-implementation-of-robotic-process-automation-rpa-in-companies-can-help-reduce-offshore-and-onshore-operations-cost-by-more-than-25-in-most-of-the-cases-industryarc-300853783.html" target="_blank">read more</a> ]
HYDERABAD, India, May 21, 2019 /PRNewswire/ -- Process automation market involves the combined usage of technology and products such as sensors, tachometers, and many others which facilitate the automation of tasks or processes in a business with minimal manu… [+8118 chars] 


