---
title: "The Problem Of Overfitting And How To Resolve It  " 
author: 
date: 2019-06-23
slug: 
categories: 
- overfitting
- readthe
- mllib
- short
- pyspark
- datascience
- AI
tags: 
- overfitting
- readthe
- mllib
- short
- pyspark
- datascience
- AI
isCJKLanguage: no 
---

## The Problem Of Overfitting And How To Resolve It   
[ <a href="https://medium.com/@farhadmalik84/the-problem-of-overfitting-and-how-to-resolve-it-1eb9456b1dfd" target="_blank">read more</a> ] 
  Explaining How To Fix The Curse Of Overfitting In Python 6 min read 




## A Technical Look at How Criminals Use AI   
[ <a href="https://medium.com/@ODSC/a-technical-look-at-how-criminals-use-ai-4080f2e325a9" target="_blank">read more</a> ] 
  Machine learning is one of the most exciting new features used in technology today. However, it is… 6 min read 




## The amazing power of long/short term memory networks (LSTMs)   
[ <a href="https://medium.com/@mdfarragher/the-amazing-power-of-long-short-term-memory-networks-lstms-b6f2c80d50ee" target="_blank">read more</a> ] 
  Long short term memory networks have both long- and short term memory, and this makes them ideal for… 3 min read 




## Multi-Class Text Classification Using PySpark, MLlib & Doc2Vec   
[ <a href="https://medium.com/@avisheknag17/multi-class-text-classification-using-pyspark-mllib-doc2vec-dbfcee5b39f2" target="_blank">read more</a> ] 
  How to use Apache Spark MLlib with PySpark for NLP problems and how to simulate Doc2Vec in Spark MLlib 6 min read 




## 'How Telecom Giants AT&T And T-Mobile Are Using Blockchain' 
 [ <a href="https://www.forbes.com/sites/benjaminpirus/2019/06/13/how-telecom-giants-att-and-t-mobile-are-using-blockchain/" target="_blank">read more</a> ]
Share to facebook
Share to twitter
Share to linkedin
AT&amp;amp;T and T-Mobile are two telecom giants working with blockchain technology in the industry.
AT&amp;amp;T
Over the past year, mainstream giants have&amp;nbsp;taken steps to incorporate&amp;nbsp… [+18352 chars] 


