---
title: "Make your JavaScript elegant with recursions  " 
author: 
date: 2019-10-14
slug: 
categories: 
- nlptask
- guide
- python
- datascience
- AI
tags: 
- nlptask
- guide
- python
- datascience
- AI
isCJKLanguage: no 
---

## Make your JavaScript elegant with recursions   
[ <a href="https://medium.com/@PurpleGreenLemon/make-your-javascript-elegant-with-recursions-98e006ab380c" target="_blank">read more</a> ] 
  A short guide 6 min read 




## Examining Gender and Race Bias in Sentiment Analysis Systems   
[ <a href="https://medium.com/@ibelmopan/examining-gender-and-race-bias-in-sentiment-analysis-systems-b04b269a653" target="_blank">read more</a> ] 
  The study determines whether sentiment analysis systems display inappropriate human biases. 6 min read 




## The Easy Guide to Python Command Line Arguments 😎   
[ <a href="https://medium.com/@george.seif94/the-easy-guide-to-python-command-line-arguments-96b4607baea1" target="_blank">read more</a> ] 
  One of the strengths of Python is that it comes with the ability to do just about anything. Its standard… 5 min read 




## Entity Linking: A primary NLP task for Information Extraction   
[ <a href="https://medium.com/@msundarv/entity-linking-a-primary-nlp-task-for-information-extraction-22f9d4b90aa8" target="_blank">read more</a> ] 
  Do you want to use the massive linked open data available? Have you heard of a significant NLP task called… 6 min read 




## 'Six Ways For Leaders To Stay Agile In The Age Of Artificial Intelligence' 
 [ <a href="https://www.forbes.com/sites/forbescoachescouncil/2019/10/08/six-ways-for-leaders-to-stay-agile-in-the-age-of-artificial-intelligence/" target="_blank">read more</a> ]
<ul><li>Share to facebook</li><li>Share to twitter</li><li>Share to linkedin</li></ul>
Over the next decade, artificial intelligence (AI) is expected to impact all kinds of industries and fundamentally shift the way we work. In an article by former McKinsey … [+12187 chars] 


