---
title: 'Signing With Alexa: A DIY Experiment in AI Accessibility'
author: 
date: 2019-06-06
slug: 
categories: 
- voiceinteractions
- ai
- learning
- ever-widening
- datascience
- AI
tags: 
- voiceinteractions
- ai
- learning
- ever-widening
- datascience
- AI
isCJKLanguage: no 
---

## Signing With Alexa: A DIY Experiment in AI Accessibility   
[ <a href="https://medium.com/@Synced/signing-with-alexa-a-diy-experiment-in-ai-accessibility-57e4407af539" target="_blank">read more</a> ] 
  With its fluent voice interactions and ever-widening library of skills, Amazon's virtual assistant Alexa… 4 min read 




## Word2Vec - a baby step in Deep Learning but a giant leap towards Natural…   
[ <a href="https://medium.com/@suvro.banerjee16/word2vec-a-baby-step-in-deep-learning-but-a-giant-leap-towards-natural-language-processing-40fe4e8602ba" target="_blank">read more</a> ] 
  Let's demystify word2vec with reasoning, examples and mathematics 10 min read 




## What is the next big thing in AI and ML?   
[ <a href="" target="_blank">read more</a> ] 
  And is there one? 16 min read 




## A Technical Look at How Criminals Use AI   
[ <a href="https://medium.com/@ODSC/a-technical-look-at-how-criminals-use-ai-4080f2e325a9" target="_blank">read more</a> ] 
  Machine learning is one of the most exciting new features used in technology today. However, it is… 6 min read 




## 'The Health Care Benefits of Combining Wearables and AI' 
 [ <a href="https://hbr.org/2019/05/the-health-care-benefits-of-combining-wearables-and-ai" target="_blank">read more</a> ]
In southeast England, patients discharged from a group of hospitals serving 500,000 people are being fitted with a Wi-Fi-enabled armband that remotely monitors vital signs such as respiratory rate, oxygen levels, pulse, blood pressure, and body temperature.
… [+7715 chars] 


