---
title: Natural Language Processing for Fuzzy String Matching with Python   
author: 
date: 2019-05-26
slug: 
categories: 
- languageprocessing
- python
- media
- fuzzy
- datascience
- AI
tags: 
- languageprocessing
- python
- media
- fuzzy
- datascience
- AI
isCJKLanguage: no 
---

## Natural Language Processing for Fuzzy String Matching with Python   
[ <a href="https://medium.com/@actsusanli/natural-language-processing-for-fuzzy-string-matching-with-python-6632b7824c49" target="_blank">read more</a> ] 
  In computer science, fuzzy string matching is the technique of finding strings that match a pattern… 5 min read 




## JIT fast! Supercharge tensor processing in Python with JIT compilation   
[ <a href="https://medium.com/@chrisvcsefalvay/jit-fast-supercharge-tensor-processing-in-python-with-jit-compilation-47598de6ee96" target="_blank">read more</a> ] 
  Numba can speed up tensor processing work in Python by an order of magnitude. Read on for one of the easiest… 11 min read 




## Machine Learning | Natural Language Preprocessing with Python   
[ <a href="https://medium.com/@mateusz.jurewicz/machine-learning-natural-language-preprocessing-with-python-5922d79d9ee2" target="_blank">read more</a> ] 
  5 Helpful Tips 9 min read 




## Simplifying Sentiment Analysis using VADER in Python (on Social Media Text)   
[ <a href="https://medium.com/@parulnith/simplifying-social-media-sentiment-analysis-using-vader-in-python-f9e6ec6fc52f" target="_blank">read more</a> ] 
  An easy to use Python library built especially for sentiment analysis of social media texts. 8 min read 




## 'Boom wants to build a supersonic jet for mainstream passengers; here’s its game plan' 
 [ <a href="http://techcrunch.com/2019/05/22/boom-wants-to-build-a-supersonic-jet-for-mainstream-passengers-heres-its-game-plan/" target="_blank">read more</a> ]
While much of the world remains fixated on the competition to build autonomous cars, there’s another race that’s gaining momentum fast. It centers on supersonic jets that can fly faster than the speed of sound, or 767 miles per hour. Indeed, while most commer… [+12004 chars] 


